import type { Metadata } from "next";
import localFont from 'next/font/local';

import "./globals.css";

import Navbar from "./Navbar";
import {CustomToaster} from '@/app/component';

const nunito = localFont({
  src: "./font/Nunito.ttf",
  variable: "--font-nuntio",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} p-3 md:p-5 antialiased`}
      >
        <Navbar />
        <main>
        {children}
        </main>
        <CustomToaster />
      </body>
    </html>
  );
}
