import type { Metadata } from "next";
import localFont from 'next/font/local'

import '@radix-ui/themes/styles.css'; 
import "./globals.css"

import { Theme } from "@radix-ui/themes";
import Navbar from "./Navbar";

const nunito = localFont({
  src: "./font/Nunito.ttf",
  variable: "--font-nuntio",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} p-5 antialiased`}
      >
      <Theme>
        <Navbar />
        <main>
        {children}</main>
      </Theme>
      </body>
    </html>
  );
}
